resources:
  - ../../base/deployment-test

configMapGenerator:
  - name: the-map
    namespace: default
    env: config.properties

secretGenerator:
  - name: the-secret
    namespace: default
    env: config.properties